# GenomeAMRAnalyzer Production Configuration
# ==========================================
# Production-ready configuration for AMR resistance gene analysis pipeline
# Supports local, HPC, and cloud deployment scenarios

# Environment Configuration
environment:
  deployment_type: "local"  # Options: local, hpc, cloud, docker
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  max_parallel_jobs: 4
  memory_limit_gb: 8
  temp_cleanup: true

# NCBI Configuration (required for genome downloads)
ncbi:
  email: "your.email@institution.edu"  # REQUIRED: Change before use
  api_key: ""  # Optional: Recommended for production use
  timeout_seconds: 300
  retry_attempts: 3
  max_genomes: 50  # Production limit (increase as needed)

# CARD Database Configuration
card:
  database_path: "data/card_database/card.json"
  auto_download: true
  update_check: true
  local_cache: true

# Analysis Pipeline Configuration
analysis:
  # Gene targets for resistance analysis
  target_genes:
    - "acrB"    # Multidrug efflux pump
    - "acrA"    # Efflux pump accessory protein  
    - "tolC"    # Outer membrane channel
    - "mexA"    # Pseudomonas efflux pump
    - "mexB"    # Pseudomonas efflux transporter
    - "oprM"    # Outer membrane protein
  
  # Quality control thresholds
  quality_control:
    min_genome_size: 1000000     # 1MB minimum
    max_genome_size: 50000000    # 50MB maximum (production limit)
    min_gene_length: 300         # 100 amino acids minimum
    min_alignment_identity: 70.0  # Minimum % identity for alignment
    min_coverage: 5              # Minimum coverage for mutation calling
    min_quality_score: 30.0      # Minimum quality score
  
  # Statistical analysis parameters
  statistics:
    cooccurrence_min_support: 0.1
    significance_threshold: 0.05
    permutation_tests: 1000
    confidence_level: 0.95

# Tool-specific Parameters
tools:
  # CARD RGI Configuration
  rgi:
    input_type: "contig"
    local_db: true
    clean_temp: true
    output_format: "json"
    threads: 4
    timeout_seconds: 600  # 10 minutes for production
    fallback_simulation: true
    coordinate_validation: true
  
  # Alignment Configuration  
  alignment:
    algorithm: "water"  # EMBOSS Water for pairwise alignment
    gap_open: 10.0
    gap_extend: 0.5
    matrix: "BLOSUM62"
    reference_fetch: true
    sepi_integration: true
  
  # Mutation Detection
  mutation_calling:
    algorithm: "statistical"
    min_coverage: 5
    min_quality: 30.0
    confidence_threshold: 0.95
    clinical_annotation: true
  
  # Network Analysis
  network:
    layout_algorithm: "spring"
    edge_weight_threshold: 0.1
    node_size_scaling: true
    export_formats: ["png", "svg", "graphml"]

# Output Directory Structure (production-ready)
directories:
  # Input/intermediate directories
  genomes: "genome_data/fasta"
  card_results: "card_results" 
  proteins: "proteins"
  alignments: "alignments"
  
  # Analysis output directories
  mutations: "mutations"
  cooccurrence: "cooccurrence"
  networks: "networks"
  
  # Final results and reports
  results: "results"
  reports: "reports"
  html_reports: "reports/html"
  
  # System directories
  logs: "logs"
  temp: "temp"
  cache: "cache"

# Performance Optimization
performance:
  batch_size: 10           # Genomes per batch
  parallel_downloads: 3    # Concurrent downloads
  memory_per_job: 2        # GB per analysis job
  disk_cache_size: 10      # GB for caching
  cleanup_temp: true       # Remove temporary files
  compress_outputs: false  # Compress large output files

# Logging and Monitoring
logging:
  level: "INFO"
  file_rotation: true
  max_log_size: "100MB"
  backup_count: 5
  performance_metrics: true
  error_notifications: false

# Production Deployment Settings
deployment:
  version: "2.0.0"
  environment: "production"
  data_retention_days: 30
  backup_results: true
  health_checks: true
  monitoring_enabled: false